title: Gregory Guevara Rodríguez

description: >
   Irrigation & Fertigation · Pressurized Hydraulics · Digital Agriculture

tagline: >
  Irrigation & Fertigation · Pressurized Hydraulics · Digital Agriculture

author:
  name: Gregory Guevara Rodríguez
  email: "gguevara@earth.ac.cr"

theme: minima

markdown: kramdown
show_excerpts: false
lang: en

url: "https://greko-guevara.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/greko-guevara" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/gguevara" }

header_pages:
  - index.md
  - research.md
  - software.md
  - teaching.md
  - professionalcareer.md
  - cv.md

